version: '3.7'

services:
    nginx:
        build: ./nginx
        volumes:
            - ./flylog_django:/usr/src/flylog_django/
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 444:443
        depends_on:
            - web
    web:
        build: ./flylog_django
        env_file:
            - .env
        environment:
            - SECRET_KEY:${SECRET_KEY}
            - CESIUM_KEY:${CESIUM_KEY}
            - ALLOWED_HOST:${ALLOWED_HOST}
        command: gunicorn --timeout 360000 flylog_django.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./flylog_django:/usr/src/flylog_django/
        expose:
            - 8000
