version: '3.7'

services:
    web:
        build: ./flylog_django
        command: /bin/sh -c "./manage.py makemigrations && ./manage.py migrate"
        volumes:
            - ./flylog_django:/usr/src/flylog_django/
            - static_volume:/usr/src/flylog_django/static/
            - media_volume:/usr/src/flylog_django/media/
        expose:
            - 8000
volumes:
    static_volume:
    media_volume:
