# Generated by Django 2.1.4 on 2018-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date published')),
                ('site', models.CharField(max_length=32)),
                ('take_off_size', models.CharField(max_length=32)),
                ('wind_speed', models.CharField(max_length=32)),
                ('wind_direction', models.CharField(max_length=32)),
                ('duration', models.PositiveSmallIntegerField()),
                ('wing', models.CharField(default='ALPHA 6, ADVANCE', max_length=32)),
                ('context', models.CharField(default='Autonomie', max_length=32)),
                ('comment', models.CharField(max_length=32)),
            ],
        ),
    ]
