# Generated by Django 2.1.4 on 2018-12-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Flight')),
            ],
        ),
    ]
