# Generated by Django 2.1.4 on 2018-12-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='flight',
        ),
    ]
