# Generated by Django 2.1.4 on 2018-12-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_remove_image_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overview.Flight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='video',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Flight'),
        ),
    ]
