# Generated by Django 2.1.4 on 2018-12-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_auto_20181218_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='take_off_size',
            new_name='take_off_site',
        ),
    ]
