# Generated by Django 2.1.4 on 2019-04-27 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_auto_20181218_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='wind_speed',
        ),
        migrations.AlterField(
            model_name='flight',
            name='comment',
            field=models.CharField(max_length=2048, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='context',
            field=models.CharField(default='Autonomie', max_length=32, verbose_name='Cadre'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='site',
            field=models.CharField(default='St Hilaire du Touvet', max_length=32, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='take_off_site',
            field=models.CharField(max_length=32, verbose_name='Déco'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='wing',
            field=models.CharField(default='ALPHA 6, ADVANCE', max_length=32, verbose_name='Aile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=256, verbose_name='Video URL'),
        ),
    ]
