# Generated by Django 2.1.4 on 2020-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0006_auto_20190427_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='take_off_site',
        ),
        migrations.AlterField(
            model_name='flight',
            name='wing',
            field=models.CharField(default='Hook 5P, NIVIUK', max_length=32, verbose_name='Aile'),
        ),
    ]
