# Generated by Django 2.1.5 on 2021-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0008_flight_igc'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_path',
            field=models.FileField(default='default, not found, surprised pikachu', upload_to='images/'),
        ),
    ]
