# Generated by Django 2.1.5 on 2021-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0009_image_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_path',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
