# Generated by Django 2.1.5 on 2021-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0010_auto_20210713_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='igc',
            field=models.FileField(blank=True, default='', upload_to='tracks/', verbose_name='Trace IGC'),
        ),
    ]
