# Generated by Django 2.1.5 on 2021-09-26 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0011_auto_20210716_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 13, 52, 55, 443756, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Durée'),
        ),
    ]
